environment:
  matrix:
    - PYTHON_HOME: "C:\\Python27"

init:
  - 'echo PYTHON_HOME=%PYTHON_HOME%'
  - ver
G
install:
  - '%PYTHON_HOME%\python.exe -V'
  - '%PYTHON_HOME%\Scripts\pip.exe --version'
  - '%PYTHON_HOME%\Scripts\pip.exe install pypiwin32'
  - ps: Start-FileDownload "http://ftp.gnome.org/pub/GNOME/binaries/win32/pygtk/2.24/pygtk-all-in-one-2.24.2.win32-py2.7.msi"
  - msiexec /i pygtk-all-in-one-2.24.2.win32-py2.7.msi /qn /norestart /log pygtk-install.log TARGETDIR=C:\Python27 ALLUSERS=1
# download Winapp.ini for TestWinapp.py
  - ps: Start-FileDownload http://www.winapp2.com/Winapp2.ini -FileName "$Env:TMP\bleachbit_test_winapp2.ini"
# build uses 7-zip, NSIS, UPX
# appveyor already has 7-zip
  - choco install nsis upx

cache:
  - pygtk-all-in-one-2.24.2.win32-py2.7.msi

build_script:
  - 'c:\mingw\bin\mingw32-make.exe -C po local'
  - windows/setup_py2exe.bat


test_script:
  - echo no test today
  #- '%PYTHON_HOME%\python.exe tests\TestAll.py'

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

