environment:
  matrix:
    - PYTHON_HOME: "C:\\Python27"

init:
  - 'echo PYTHON_HOME=%PYTHON_HOME%'
  - ver

install:
  - '%PYTHON_HOME%\python.exe -V'
  - '%PYTHON_HOME%\Scripts\pip.exe --version'
  - '%PYTHON_HOME%\Scripts\pip.exe install pypiwin32'
  - ps: Start-FileDownload "http://ftp.gnome.org/pub/GNOME/binaries/win32/pygtk/2.24/pygtk-all-in-one-2.24.2.win32-py2.7.msi"
  - msiexec /i pygtk-all-in-one-2.24.2.win32-py2.7.msi /qn /norestart /log pygtk-install.log TARGETDIR=C:\Python27 ALLUSERS=1
# download Winapp.ini for TestWinapp.py
  - ps: Start-FileDownload http://www.winapp2.com/Winapp2.ini -FileName "$Env:TMP\bleachbit_test_winapp2.ini"
# build uses 7-zip, NSIS, UPX
# appveyor already has 7-zip
  - appveyor DownloadFile "https://sourceforge.net/projects/nsis/files/NSIS 2/2.50/nsis-2.50-setup.exe/download" -FileName nsis-setup.exe
  - nsis-setup.exe /S /D="c:\Program Files\NSIS"
  - appveyor DownloadFile http://upx.sourceforge.net/download/upx391w.zip -FileName upx.zip
  - 7z x upx.zip

cache:
  - pygtk-all-in-one-2.24.2.win32-py2.7.msi

build_script:
  - windows/setup_py2exe.bat


test_script:
 - '%PYTHON_HOME%\python.exe tests\TestAll.py'
